name: default

on: [push, pull_request]

jobs:
  format:
    name: Run StyLua
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: JohnnyMorganz/stylua-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: 0.20.0
        args: --check .
